// frontend/packages/shared-ui/src/react/Card.tsx
import * as React from 'react';

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  hoverable?: boolean;
}

export const Card: React.FC<CardProps> = ({
  children,
  hoverable = false,
  className = '',
  ...props
}) => {
  return (
    <div
      className={`bg-white rounded-lg shadow-md p-6 border border-gray-100 transition-all duration-200 ${
        hoverable ? 'hover:shadow-lg hover:-translate-y-0.5' : ''
      } ${className}`}
      {...props}
    >
      {children}
    </div>
  );
};

// frontend/packages/shared-ui/src/vue/Card.vue
<template>
  <div
    :class="[
      'bg-white rounded-lg shadow-md p-6 border border-gray-100 transition-all duration-200',
      hoverable ? 'hover:shadow-lg hover:-translate-y-0.5' : ''
    ]"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>

<script setup>
defineProps({
  hoverable: {
    type: Boolean,
    default: false
  }
});
</script>
